### ISSUE TITLE
Error: Property 'lvalue' not found when creating a list

### ISSUE THREAD

**Issue by ShivankKhullar** [bdlm-dev/todo-list-app#1]
When attempting to create a new list through the application's UI, an error is thrown related to a property 'lvalue' not being found. This issue seems to occur during the list creation process and may be related to the state management or rendering logic.

Steps to Reproduce

1. Navigate to the main page of the application.
2. Click on the plus (+) button to bring up the creation options.
3. Select 'List' from the creation options.
4. Attempt to create a list.

Behavior:
An error is thrown, stating that a property 'lvalue' is not found, which prevents the list from being created.

Additional Information
Environment: Expo Go Android

I understand that the application is still under development, and this issue may already be on your radar. I wanted to report it to ensure that it's tracked and can be addressed accordingly.

Screenshots:
<img width="257" alt="Screenshot 2023-11-08 224413" src="https://github.com/bdlm-dev/todo-list-app/assets/121053144/48e07670-9bcb-4a42-8745-242204ea2971">

**Comment by bdlm-dev** [comment]
Thanks for the heads-up, the property 'lvalue' shouldn't have even existed after a refactor so was a simple rename to fix; has been fixed with commit d0439ab
